### ISSUE TITLE
What is motivation of choosing JAX as basis?

### ISSUE THREAD

**Issue by fengsxy** [cbg-ethz/bmi#167]
There are more and more neural estimators, which are implemented using PyTorch. I feel that using JAX contributes to some troubles for future implementations. This means that for every new estimator, a JAX version is required, which is very difficult.

**Comment by pawel-czyz** [comment]
Hi, thanks for reaching out! We picked JAX because it is light, fast, and offers excellent support for reproducible random number generation. Also, since v2 we rely on TensorFlow Probability on JAX for the tasks based on Bend and Mix Models. However, if your estimator is implemented in PyTorch, there are three options.

First, you can use our package as a dependency – for example, [MINDE](https://github.com/MustaphaBounoua/minde) does this.

As a second option, you can e.g., fork the repository and use PyTorch as an optional dependency. We have a Bayesian estimator built in NumPyro, so in `pyproject.toml` we have an optional dependency:

```toml
[tool.poetry.group.bayes]
optional = true

[tool.poetry.group.bayes.dependencies]
numpyro = "^0.14.0"
```

As a third option, the external API (see `bmi/src/bmi/estimators/external`) allows one to add estimators written in any programming language (e.g., we used estimators implemented in R and Julia).

Finally, we would be happy to give some help with a JAX implementation of your PyTorch estimator :slightly_smiling_face:

**Comment by fengsxy** [comment]
Thank you for your reply.
Does that mean PyTorch does not offer excellent support for reproducible random number generation?

**Comment by pawel-czyz** [comment]
I personally find PyTorch an excellent and very well-developed framework. It has many great and stable utilities, including very nice support for random number generators. I (subjectively and this is a personal preference) prefer the JAX way of handling the random state, though :slightly_smiling_face:

**Comment by fengsxy** [comment]
Thanks! I got it. This issue could be closed.
