### ISSUE TITLE
Unable to Build pands._lib.algos

### ISSUE THREAD

**Issue by matthewdmanning** [cbg-ethz/bmi#169]
Python == 3.12.0; benchmark-mi == 0.1.3 (also tried 0.1.2), pandas == 2.2.2
Installed Visual C++ 14 Build Tools from MS website. Also, downloaded dependencies in requirements.txt.
Attempted to install via Pycharm Community, as well as through Windows terminal.

It appears that the installer is unable to use a slicing function from pandas. The pyproject.toml file lists pands == '^1.5.3', but the current pandas release is 2.2.2. Could this be causing the issue?

_Installation Output_
  UPDATING build\lib.win-amd64-cpython-312\pandas/_version.py
  set build\lib.win-amd64-cpython-312\pandas/_version.py to '1.5.3'
  running build_ext
  building 'pandas._libs.algos' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pandas)

**Comment by pawel-czyz** [comment]
Hi, thanks for submitting the issue! I currently don't have access to Windows, but I think one solution may be the following:
1. Configuring a WSL2 terminal: https://learn.microsoft.com/en-us/windows/wsl/install and then
2. Creating a fresh [Micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) environment set to Python 3.11.
3. Installing from source. I think the current version should work (but this will also allow you to try "^2.2.2", rather than "^1.5.3", in case this version is needed.)

**Comment by pawel-czyz** [comment]
Hi, closing this issue for now – if more help would be needed, please free to reopen! :slightly_smiling_face:
